### ISSUE TITLE
Images work on localhost but not on deployed website

### ISSUE THREAD

**Issue by omeiirr** [omeiirr/SDE-Handbook#1]
Image links are broken on deployed website. 
[Example](https://omeiirr.github.io/SDE-Handbook/#/software-development/devops/docker/CI_CD_Overview).

Try running on localhost:
```bash
npm i docsify-cli -g
cd docs
docsify serve
```

**Comment by saivasanth528** [comment]
Hi, can you provide the details about your project , what is the tech-stack and can you update the readme file, if everything is good, I am happy to take this issue 👍

**Comment by omeiirr** [comment]
@saivasanth528 Done 👍🏻 
Feel free to ask if you face any problems

**Comment by saivasanth528** [comment]
Can I take this issue ??

**Comment by omeiirr** [comment]
Yes please
Assigning this to you

**Comment by saivasanth528** [comment]
Thanks , i will start working on it .

**Comment by saivasanth528** [comment]
Can you make your master branch as default branch instead of the main branch , and do the following procedure and check whether the images are loading fine or not 

https://docsify.js.org/#/deploy?id=github-pages

**Comment by saivasanth528** [comment]
can you check your website link, why it is displaying the content of readme.md file , instead of actual content ??

**Comment by omeiirr** [comment]
Same question
I changed the source for GitHub pages from branch `main /docs` to `branch main / (root)`
It broke and now neither is working

**Comment by saivasanth528** [comment]
I think its working now, but still some images got broken right ?

**Comment by saivasanth528** [comment]
Ok, the website is up now, i will work thanks

**Comment by omeiirr** [comment]
Ah, found the culprit

The site broke when I made [this](https://github.com/omeiirr/SDE-Handbook/commit/d177a230e0798d19dc28a90dff6f5157624e1321) commit
Reverted with [this](https://github.com/omeiirr/SDE-Handbook/commit/f386dde42702a5e8a93d1068b63bf076f68479ca) commit

The first commit had solved the broken images in the preview section of the markdown file (I changed directly from GitHub) but broke the whole site.

So far, what we know is, images should be linked as `![CI-CD Overview](/docs/media/images/CI_CD_Overview.png)` 
and not `<img src='/media/images/CI_CD_Overview.png' title='CI-CD Overview'/>`

Now how to do this without breaking the whole site is the question.

**Comment by saivasanth528** [comment]
ok, good insights, i am figuring out that

**Comment by saivasanth528** [comment]
PR raised, please check

**Comment by saivasanth528** [comment]
If you are satisfied, you can also close the issue

**Comment by omeiirr** [comment]
Umm, it still shows image links broken 🤔 

![image](https://user-images.githubusercontent.com/54888682/135707046-12794bd1-7886-4d4f-be96-a8ea8f05e5b2.png)

**Comment by saivasanth528** [comment]
It takes time to update , please wait for 5 minutes

**Comment by saivasanth528** [comment]
<img width="1792" alt="Screenshot 2021-10-02 at 12 35 56 PM" src="https://user-images.githubusercontent.com/24267212/135707129-e60f6bd0-e991-428c-aaff-39e3079630a3.png">

Its working for me, may be it is showing from your browser cache, please try to open in other browser or in incognito mode

**Comment by omeiirr** [comment]
Ah yes! It's fixed now.

Thanks for all the help 😄😄
