### ISSUE TITLE
Add contributing guide

### ISSUE THREAD

**Issue by omeiirr** [omeiirr/SDE-Handbook#4]

**Comment by ManasBhilare** [comment]
i would love to work on it!

**Comment by omeiirr** [comment]
Please do!
Suggest the changes that you'd like to add here and then you can raise a PR

**Comment by ManasBhilare** [comment]
would add Pull Request Process, Code of Conduct:,Responsibilities, standards etc.
should I raise a PR?

**Comment by omeiirr** [comment]
Sure

**Comment by ManasBhilare** [comment]
Thank you! @omeiirr I have added it and raised a PR for the same!

**Comment by ManasBhilare** [comment]
@omeiirr i have done the changes! And also raised a PR

**Comment by omeiirr** [comment]
Hey sorry, missed your message notifications. I have reviewed the PR and a lot of the stuff is not required, namely, the sections with code of conduct, pledge, responsibilities, scope, and enforcement.

A simple guide with the instructions to run the project locally, doing the changes in a separate branch, and raising the PR against the main branch of the original repository would be enough. 

Please take a look at the "Setup and Such" section of [this](https://github.com/jonschwartz/steffi/blob/main/CONTRIBUTING.md) guide for a sample.

**Comment by ManasBhilare** [comment]
@omeiirr i have done the changes can you please review the PR
